import "../styles/globals.css"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"

import Head from "next/head"
import Layout from "../components/layout"
import React from "react"
import { useState } from "react"

const TimelineContext = React.createContext()

function MyApp({ Component, pageProps }) {
  const [timelinePoint, setTimelinePoint] = useState(0)

  return (
    <TimelineContext.Provider value={{ timelinePoint, setTimelinePoint }}>
      <Head>
        <title>{timelinePoint}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </TimelineContext.Provider>
  )
}

export { TimelineContext }
export default MyApp
