import "../styles/globals.css"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"

import Head from "next/head"
import Layout from "../components/layout"
import React from "react"
import { useAudio } from "../hooks/useAudio"
import { useState } from "react"

const TimelineContext = React.createContext()
const BgMusicContext = React.createContext()

function MyApp({ Component, pageProps }) {
  const [timelinePoint, setTimelinePoint] = useState(0)
  const [playing, play, pause, stop, mute, isMute] = useAudio("/sound/1.mp3")
  return (
    <BgMusicContext.Provider value={{ playing, play, pause, stop, mute, isMute }}>
      <TimelineContext.Provider value={{ timelinePoint, setTimelinePoint }}>
        <Head>
          <title>เมี้ยนมลาย</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/fav.ico" />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </TimelineContext.Provider>
    </BgMusicContext.Provider>
  )
}

export { TimelineContext, BgMusicContext }
export default MyApp
