import { useEffect, useRef } from "react";

import Head from "next/head";
import ScrollTrigger from "gsap/dist/ScrollTrigger";
import gsap from "gsap/dist/gsap";

const Home = () => {
  gsap.registerPlugin(ScrollTrigger);
  const TextRef = useRef();

  useEffect(() => {
    const sections = gsap.utils.toArray(".panel");
    gsap.to(sections, {
      xPercent: -400,
      ease: "none",
      scrollTrigger: {
        trigger: ".scroll-container",
        pin: true,
        scrub: 1,
        snap: 1 / (sections.length - 1),
        end: "+=5000",
      },
    });
  }, []);

  const parallax = (e) => {
    const { pageX, pageY } = e;
    const x = (window.innerWidth - pageX)/95;
    const y = (window.innerHeight - pageY)/95;
    TextRef.current.style.transform = `translateX(${x}px) translateY(${y}px)`;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen flex justify-center items-center" onMouseMove={(e) => parallax(e)}>
        <h1 className="text-9xl" ref={TextRef}>
          Content 1
        </h1>
      </div>
      <div className="scroll-container max-w-screen h-screen flex bg-blue-500 hide-scrollbar overscroll-none">
        <div className="panel w-screen h-screen flex-shrink-0 bg-red-500 border border-black flex justify-center items-center">
          <h1 className="text-9xl">1</h1>
        </div>
        <div className="panel w-screen h-screen flex-shrink-0 bg-red-600 border border-black flex justify-center items-center">
          <h1 className="text-9xl">2</h1>
        </div>
        <div className="panel w-screen h-screen flex-shrink-0 bg-red-700 border border-black flex justify-center items-center">
          <h1 className="text-9xl">3</h1>
        </div>
        <div className="panel w-screen h-screen flex-shrink-0 bg-red-800 border border-black flex justify-center items-center">
          <h1 className="text-9xl">4</h1>
        </div>
        <div className="panel w-screen h-screen flex-shrink-0 bg-red-900 border border-black flex justify-center items-center">
          <h1 className="text-9xl">5</h1>
        </div>
      </div>
      <div className="w-full h-screen flex justify-center items-center">
        <h1 className="text-9xl">Content 2</h1>
      </div>
    </>
  );
};

export default Home;
